version: "3"

tasks:
  arxiv:
    cmds:
      - rm -rf _build/arxiv
      - mkdir -p _build/arxiv
      - mkdir -p _build/arxiv/tex
      - latexmk -pdf -interaction=nonstopmode
      - |
        cp -r \
          main.bbl \
          jss.bst \
          jss.cls \
          jsslogo.jpg \
          main.tex \
          images/ \
          _build/arxiv/
        cp -r tex/macros.tex _build/arxiv/tex/
      - rm -f _build/arxiv-{{.DATE}}.tar.gz
      - cd _build/arxiv && tar -czf ../arxiv-{{.DATE}}.tar.gz .
      - rm -rf _build/arxiv-temp
    vars:
      DATE:
        sh: date +%Y%m%d

  get-packages:
    desc: "Download required external packages"
    vars:
      CPP_VER: 6.5.0
      PYTHON_VER: 1.9.0
      R_VER: 2.0.0
      JULIA_VER: 1.3.0
    cmds:
      - rm -rf _build/packages
      - mkdir -p _build/packages/
      - curl -L -o _build/packages/libslope-{{.CPP_VER}}.tar.gz
        "https://github.com/jolars/libslope/archive/refs/tags/v{{.CPP_VER}}.tar.gz"
      - curl -L -o _build/packages/sortedl1-{{.PYTHON_VER}}.tar.gz
        "https://github.com/jolars/sortedl1/archive/refs/tags/v{{.PYTHON_VER}}.tar.gz"
      - curl -L -o _build/packages/SLOPE-{{.R_VER}}.tar.gz
        "https://github.com/jolars/SLOPE/archive/refs/tags/v{{.R_VER}}.tar.gz"
      - curl -L -o _build/packages/SLOPE-jl-{{.JULIA_VER}}.tar.gz
        "https://github.com/jolars/SLOPE.jl/archive/refs/tags/v{{.JULIA_VER}}.tar.gz"

  jss-submission:
    desc: "Prepare JSS submission bundle"
    deps:
      - get-packages
    cmds:
      - rm -rf _build/jss
      - mkdir -p _build/jss/paper
      - latexmk -pdf -interaction=nonstopmode
      - git archive --format=tar HEAD | tar -x -C _build/jss/paper
      - git submodule foreach --recursive 'git archive --format=tar HEAD | tar
        -x -C $toplevel/_build/jss/paper/$sm_path'
      - cp -r main.pdf cover-letter.pdf _build/jss/
      - |
        cp -r \
          _build/packages/ \
          _build/jss/
      - |
        cd _build/jss/paper/benchmark_slope && rm -rf \
          README.rst \
          .github \
          example_config.py \
          test_config.py
      - |
        cd _build/jss/paper/benchmark_slope_path && rm -rf \
          README.md \
          .github \
          example_config.py \
          test_config.py
      - |
        cd _build/jss/paper && \
        find . -name ".*" -type f -delete && \
        rm -rf .git .github Taskfile.yml && \
        rm -f cover-letter*.tex cover-letter*.pdf jss-example.* comments.md
      - cd _build/jss/paper && tar -czf ../replication-material.tar.gz .
      - rm -rf _build/jss/paper
      - cd _build/jss && tar -czf ../jss-{{.DATE}}.tar.gz .
    vars:
      DATE:
        sh: date +%Y%m%d
