version: "3"

tasks:
  arxiv:
    cmds:
      - rm -rf _build/arxiv
      - mkdir -p _build/arxiv
      - latexmk -pdf -interaction=nonstopmode
      - |
        cp -r \
          main.bbl \
          jss.bst \
          jss.cls \
          jsslogo.jpg \
          main.tex \
          images/ \
          tex/ \
          _build/arxiv/
      - rm -f _build/arxiv-{{.DATE}}.tar.gz
      - cd _build/arxiv && tar -czf ../arxiv-{{.DATE}}.tar.gz .
      - rm -rf _build/arxiv-temp
    vars:
      DATE:
        sh: date +%Y%m%d
